### ISSUE TITLE
Misleading Readme ?

### ISSUE THREAD

**Issue by eMerzh** [sbarratt/flask-prometheus#1]
Hi, 
I'm interested in using your module in my app, 
but i can't , it give me : 

```
$ python run.py
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from prometheus_client import monitor
ImportError: cannot import name monitor
```

am i doing something wrong ?

Thanks for your nice addition to prometheus_client :) 

edit:
using flask 10.0.1 with python 2.7

**Comment by eMerzh** [comment]
mmh should'nt be 

> from flask_prometheus import monitor 

instead of 

> from prometheus_client import monitor

in the readme ?

**Comment by dabcoder** [comment]
Indeed, as referenced in PR #2.

**Comment by eMerzh** [comment]
ok i think it's close now :)
